### ISSUE TITLE
I am having problems with the SNES and Genesis scripts

### ISSUE THREAD

**Issue by jayp76** [mrchrisster/attract_mode#1]
It only opens the menu.
Arcade, MegaCD, NeoGeo and TG16 scripts are working.
I thought it might be a problem with boot.rom. But after removing SNES boot.rom, still same behaviour.
Tried if Games folders are case sensitive, still same behaviour.

**Comment by mrchrisster** [comment]
Snes and Genesis are currently using a different method to mount the games (no " !MBC" folder being created). I've observed this problem with Snes and Genesis as well and might switch all cores to the same mount method to mitigate the problem. Thanks for reporting!

**Comment by mrchrisster** [comment]
Problem is fixed now, turns out it was a problem with Attract_Mode.sh logic and not mbc.
