### ISSUE TITLE
cifs support?

### ISSUE THREAD

**Issue by MAME-GETTER** [mrchrisster/attract_mode#4]
Please add cifs support.

**Comment by mrchrisster** [comment]
Cifs should be working fine, that's what I'm using as my dev environment. Did you mount over the games folders in /media/fat/games? That's currently the supported way.

**Comment by mrchrisster** [comment]
``` 
SERVER="192.168.1.10"  
SHARE="Games/Games - Mister/Games"  
LOCAL_DIR="*"  
BASE_PATH="/media/fat/Games" 
```
  
Here is a sample config of how I set up cifs_mount.sh

**Comment by Mellified** [comment]
@MAME-GETTER Please share your CIFS config - WITHOUT PASSWORDS - so we can investigate.
